# Site settings

title: Bridge & Bubble # Title of your site
email: # Your contact email

description: I'm Hoang-Anh. This is my personal blog of wanderful bridges and wonderful bubbles.
keywords: bridge, bubble, wander, wonder, personal blog, hoanganhphan, Hoang-Anh Phan
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bridgeandbubble.com" # the base hostname & protocol for your site

timezone: Asia/Hanoi
locale: en_uk
icon:

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

twitter_username:     hoanganhphan # Replace this with your Twitter username
github_username:      chichgu # Replace this with your GitHub username
linkedin_username:    hoanganh # Replace this with your LinkedIn username
google_plus_username:	+HoangAnhPhanHAP # Replace this with your Google+ username
facebook_username:    chichgu # Replace this with your Facebook username
dribbble_username:    # Replace this with your Dribbble username

# Build settings
markdown: kramdown
